#!/bin/sh

# PROVIDE: v2ray
# REQUIRE: LOGIN
# BEFORE:  securelevel
# KEYWORD: shutdown

# Add the following line to /etc/rc.conf to enable `v2ray':
#
#v2ray_enable="YES"
#

. /etc/rc.subr

name="v2ray"
rcvar="${name}_enable"

command="/usr/local/bin/v2ray"
pidfile="/var/run/$name.pid"

# read configuration and set defaults
load_rc_config "$name"
: ${v2ray_enable="NO"}
: ${v2ray_user="v2ray"}
: ${v2ray_config="/usr/local/etc/$name/config.json"}

command_args="-config ${v2ray_config}"
required_files="${v2ray_config}"

export V2RAY_LOCATION_ASSET=/usr/local/share/$name

v2ray_start() {
	mkdir -p /var/log/v2ray
	chown -R v2ray:v2ray /var/log/v2ray
        /usr/sbin/daemon -u ${v2ray_user} -p ${pidfile} ${command} ${command_args}
}

v2ray_status() {
        if [ -e ${pidfile} ]; then
                echo ${name} is running.
        else
                echo ${name} is not running.
        fi
}

v2ray_stop() {
        if [ -e ${pidfile} ]; then
                kill `cat ${pidfile}`;
        else
                echo ${name} is not running?
        fi
}

start_cmd="v2ray_start"
stop_cmd="v2ray_stop"
status_cmd="v2ray_status"

run_rc_command "$1"
