#!/bin/sh

# PROVIDE: v2ray
# REQUIRE: LOGIN
# BEFORE:  securelevel
# KEYWORD: shutdown

# Add the following line to /etc/rc.conf to enable `v2ray':
#
#v2ray_enable="YES"
#

. /etc/rc.subr

name="v2ray"
rcvar="${name}_enable"

: ${v2ray_enable="NO"}
: ${v2ray_user="v2ray"}
: ${v2ray_group="v2ray"}
: ${v2ray_env="V2RAY_LOCATION_ASSET=/usr/local/share/$name"}
: ${v2ray_config="/usr/local/etc/$name/config.json"}

logdir="var/log/$name"
pidfile="/var/run/$name.pid"
procname="/usr/local/bin/$name"
command="/usr/sbin/daemon"
command_args="-f -c -p ${pidfile} /usr/bin/env ${v2ray_env} ${procname} -config ${v2ray_config}"
required_files="${v2ray_config}"

start_precmd="v2ray_startprecmd"

v2ray_startprecmd() {
	if [ ! -e "${pidfile}" ]; then
		install -o "${v2ray_user}" -g "${v2ray_group}" "/dev/null" "${pidfile}"
	fi
	if [ ! -d "${logdir}" ]; then
		install -o "${v2ray_user}" -g "${v2ray_group}" -d  "${logdir}"
	fi
}

load_rc_config "$name"
run_rc_command "$1"
